[INFO   ] Logger: Record log in C:/Users/bharkins/Desktop/news\logs\kivy_20-01-15_9.txt
[INFO   ] deps: Successfully imported "kivy_deps.gstreamer" 0.2.0
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.2.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.2.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.2.0
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\python.exe"
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.5.0 NVIDIA 358.87'>
[INFO   ] GL: OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] GL: OpenGL renderer <b'Quadro K2200/PCIe/SSE2'>
[INFO   ] GL: OpenGL parsed version: 4, 5
[INFO   ] GL: Shading version <b'4.50 NVIDIA'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <32>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "kivy\properties.pyx", line 1396, in kivy.properties.ReferenceListProperty.get
[WARNING] stderr:   File "kivy\properties.pyx", line 1273, in kivy.properties.ObservableReferenceList.__setslice__
[WARNING] stderr: AttributeError: type object 'list' has no attribute '__setslice__'
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
[WARNING] stderr:     return eval(value, idmap), bound_list
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\data\style.kv", line 257, in <module>
[WARNING] stderr:     pos: self.pos
[WARNING] stderr:   File "kivy\weakproxy.pyx", line 32, in kivy.weakproxy.WeakProxy.__getattr__
[WARNING] stderr:   File "kivy\properties.pyx", line 508, in kivy.properties.Property.__get__
[WARNING] stderr:   File "kivy\properties.pyx", line 1400, in kivy.properties.ReferenceListProperty.get
[WARNING] stderr:   File "kivy\properties.pyx", line 1268, in kivy.properties.ObservableReferenceList.__setitem__
[WARNING] stderr: RecursionError: maximum recursion depth exceeded while calling a Python object
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 920, in _build_canvas
[WARNING] stderr:     key, value, prule, idmap, True)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 254, in create_handler
[WARNING] stderr:     cause=tb)
[WARNING] stderr: kivy.lang.builder.BuilderException: Parser: File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\data\style.kv", line 257:
[WARNING] stderr: ...
[WARNING] stderr:     255:        StencilPush
[WARNING] stderr:     256:        Rectangle:
[WARNING] stderr: >>  257:            pos: self.pos
[WARNING] stderr:     258:            size: self.size
[WARNING] stderr:     259:        StencilUse
[WARNING] stderr: ...
[WARNING] stderr: RecursionError: maximum recursion depth exceeded while calling a Python object
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
[WARNING] stderr:     return eval(value, idmap), bound_list
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\data\style.kv", line 257, in <module>
[WARNING] stderr:     pos: self.pos
[WARNING] stderr:   File "kivy\weakproxy.pyx", line 32, in kivy.weakproxy.WeakProxy.__getattr__
[WARNING] stderr:   File "kivy\properties.pyx", line 508, in kivy.properties.Property.__get__
[WARNING] stderr:   File "kivy\properties.pyx", line 1400, in kivy.properties.ReferenceListProperty.get
[WARNING] stderr:   File "kivy\properties.pyx", line 1268, in kivy.properties.ObservableReferenceList.__setitem__
[WARNING] stderr: 
[WARNING] stderr: 
[WARNING] stderr: During handling of the above exception, another exception occurred:
[WARNING] stderr: 
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "<input>", line 1, in <module>
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
[WARNING] stderr:     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
[WARNING] stderr:     exec(compile(contents+"\n", file, 'exec'), glob, loc)
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 220, in <module>
[WARNING] stderr:     TheMain().run()
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 829, in run
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 39, in build
[WARNING] stderr:     sm.add_widget(SummaryPage(name="SummaryPage"))
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 120, in __init__
[WARNING] stderr:     self.load_titles_to_page(self)
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 131, in load_titles_to_page
[WARNING] stderr:     self.load_titles_to_page()
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 131, in load_titles_to_page
[WARNING] stderr:     self.load_titles_to_page()
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 131, in load_titles_to_page
[WARNING] stderr:     self.load_titles_to_page()
[WARNING] stderr:   [Previous line repeated 965 more times]
[WARNING] stderr:   File "C:/Users/bharkins/Desktop/news/reader.py", line 123, in load_titles_to_page
[WARNING] stderr:     root = ScrollView()
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\scrollview.py", line 513, in __init__
[WARNING] stderr:     super(ScrollView, self).__init__(**kwargs)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 361, in __init__
[WARNING] stderr:     rule_children=rule_children)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\uix\widget.py", line 469, in apply_class_lang_rules
[WARNING] stderr:     rule_children=rule_children)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 538, in apply
[WARNING] stderr:     rule_children=rule_children)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 592, in _apply_rule
[WARNING] stderr:     rule.canvas_before, rootrule)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 926, in _build_canvas
[WARNING] stderr:     '{}: {}'.format(e.__class__.__name__, e), cause=tb)
[WARNING] stderr: kivy.lang.builder.BuilderException: Parser: File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\data\style.kv", line 257:
[WARNING] stderr: ...
[WARNING] stderr:     255:        StencilPush
[WARNING] stderr:     256:        Rectangle:
[WARNING] stderr: >>  257:            pos: self.pos
[WARNING] stderr:     258:            size: self.size
[WARNING] stderr:     259:        StencilUse
[WARNING] stderr: ...
[WARNING] stderr: BuilderException: Parser: File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\data\style.kv", line 257:
[WARNING] stderr: ...
[WARNING] stderr:     255:        StencilPush
[WARNING] stderr:     256:        Rectangle:
[WARNING] stderr: >>  257:            pos: self.pos
[WARNING] stderr:     258:            size: self.size
[WARNING] stderr:     259:        StencilUse
[WARNING] stderr: ...
[WARNING] stderr: RecursionError: maximum recursion depth exceeded while calling a Python object
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
[WARNING] stderr:     return eval(value, idmap), bound_list
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\data\style.kv", line 257, in <module>
[WARNING] stderr:     pos: self.pos
[WARNING] stderr:   File "kivy\weakproxy.pyx", line 32, in kivy.weakproxy.WeakProxy.__getattr__
[WARNING] stderr:   File "kivy\properties.pyx", line 508, in kivy.properties.Property.__get__
[WARNING] stderr:   File "kivy\properties.pyx", line 1400, in kivy.properties.ReferenceListProperty.get
[WARNING] stderr:   File "kivy\properties.pyx", line 1268, in kivy.properties.ObservableReferenceList.__setitem__
[WARNING] stderr: 
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 920, in _build_canvas
[WARNING] stderr:     key, value, prule, idmap, True)
[WARNING] stderr:   File "C:\Users\bharkins\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\lang\builder.py", line 254, in create_handler
[WARNING] stderr:     cause=tb)
[WARNING] stderr: 
